export enum Status {
    PENDING = 'PENDING',
    SUBMITTED = 'SUBMITTED',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    WITHDRAWN = 'WITHDRAWN',
    DOCUMENT_REQUIRED = 'DOCUMENT_REQUIRED'
  }