export enum UserStatus {
    NEWUSER = 'NEW_USER',
    REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
    REQUESTED_MOREDETAILS = 'REQUESTED_MOREDETAILS',
    IN_REVIEW = 'IN_REVIEW',
    VERIFIEDUSER = 'VERIFIED_USER',
    BLOCKED = 'BLOCKED',
    DELETED = 'DELETED',
    WITHDRAWN = 'WITHDRAWN',
  }