export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const POST_MODEL = 'POST_MODEL';
export const USER_MODEL = 'USER_MODEL';
export const COMMENT_MODEL = 'COMMENT_MODEL';
export const PROFILE_MODEL = 'PROFILE_MODEL';
export const ACCOUNT_CONFIG_MODEL = 'ACCOUNT_CONFIG_MODEL';
export const STORAGE_CONFIG_MODEL = 'STORAGE_CONFIG_MODEL';
export const USER_REVIEW_CONFIG_MODEL = 'USER_REVIEW_CONFIG_MODEL';
export const JOB_POST_MODEL = 'JOB_POST_MODEL';


export const DEFAULT_CREDITS = 30;

